---
- name: update all packages
  apt: name=* state=latest
  become: yes
- name: install bd packages
  apt:
    name: "{{ bd_packages }}"
    state: present
  become: yes
- name: run mysql installation
  script: 
    cmd: mysql_installation.sh
- name: Restart service httpd
  ansible.builtin.service:
    name: mysql
    state: restarted
