---
- name: "Install common packages"
  hosts: all
  tasks:
    - name: update all packages
      yum: name=* state=latest
    - name: install git
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
