---
- name: "Playbook to Add Key to Newly Provisioned EC2 Instance"
  hosts: servers
  vars:
    - status : "present"
    - key : "~/.ssh/id_rsa.pub"

  tasks:

  - name: "Copy the authorized key file from"
    authorized_key:
      user: "ec2-user"
      state: "{{status}}"
      key: "{{ lookup('file', '{{ key }}')}}"
