---
- name: "Playbook to Add Key to Newly Provisioned EC2 Instance"
  hosts: all
  vars:
    - status : "present"
    - key : "~/.ssh/id_rsa.pub"
    - ansible_ssh_common_args : "-o StrictHostKeyChecking=no"
    - ansible_user : "ubuntu"

  tasks:

  - name: "Copy the authorized key file from"
    authorized_key:
      user: "ubuntu"
      state: "{{status}}"
      key: "{{ lookup('file', '{{ key }}')}}"
