---
- name: update servers
  hosts: servers
  tasks:
  - name: update all packages
    yum: name=* state=latest

- name: install new packages
  hosts: servers
  tasks:
  - name: install git
    yum: name=git state=latest
