---
- name: update all packages
  apt: name=* state=latest
  become: yes
- name: get nodejs repository
  shell:
    cmd: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash
- name: install api packages
  apt:
    name: "{{ api_packages }}"
    state: present
  become: yes
- name: git checkout
  git:
    repo: 'https://github.com/juan-bol/movie-analyst-api.git'
    dest: ~/
- name: Change working directory to /movie-analyst-api and install app packages
  shell:
    cmd: npm install
    chdir: /movie-analyst-api
- name: Populate data base
  shell:
    cmd: mysql -h 192.168.100.13 -P 3306 --user="root" --password="holi" movie_db < ./data_model/table_creation_and_inserts.sql
- name: Change working directory to /movie-analyst-api and create data base password file
  shell:
    cmd: echo "holi" >> .secrets
    chdir: /movie-analyst-api
- name: Change working directory to /movie-analyst-api and run app
  shell:
    cmd: sudo node server.js &
    chdir: /movie-analyst-api
